---
name: Build GMS APK
"on":
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/trunk-build.yaml"
      - ".github/workflows/build-test-lint.yaml"
      - ".github/workflows/release.yaml"
      - "project/app/src/**"
      - "project/app/*.pro"
      - "project/buildSrc/src/**"
      - "project/*.gradle.kts"
      - "project/app/*.gradle.kts"
      - "project/gradle.properties"
      - "project/gradle/gradle-wrapper.properties"
      - "project/gradle/libs.versions.toml"

concurrency:
  group: ${{ github.workflow }}-default

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=true -Dorg.gradle.configuration-cache=true -Dorg.gradle.parallel=true -Dorg.gradle.caching=true -Dorg.gradle.jvmargs='-Xmx3096M -Dkotlin.daemon.jvm.options=-Xmx2048M -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC'"
jobs:
  build:
    name: Build GMS APK
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Create keystore
        run: |
          echo -n "${KEYSTORE_BASE64}" | base64 -d > project/owntracks.release.keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Build signed GMS release APK
        uses: ./.github/actions/gradle-task
        with:
          task: assembleGmsRelease ktfmtCheck
          gradle-cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
        env:
          KEYSTORE_PASSPHRASE: ${{ secrets.KEYSTORE_PASSPHRASE }}
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

      - name: Save APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: patryk-osmand-tracker-gms-release-apk
          path: project/app/build/outputs/apk/gms/release/app-gms-release.apk
          if-no-files-found: error
